AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB table for Reimbursement System'

Resources:
  ReimbursementTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ReimbursementSystem
      BillingMode: PAY_PER_REQUEST 
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: username
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: UsernameIndex
          KeySchema:
            - AttributeName: username
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: UserTicketsIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: TicketStatusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: ReimbursementSystem

Outputs:
  TableName:
    Description: Name of the DynamoDB table
    Value: !Ref ReimbursementTable
  TableArn:
    Description: ARN of the DynamoDB table
    Value: !GetAtt ReimbursementTable.Arn